### ISSUE TITLE
total_rows in response

### ISSUE THREAD

**Issue by chandu0101** [nolanlawson/pouchdb-quick-search#25]
can we get total_rows in response similar to allDocs ?

**Comment by nolanlawson** [comment]
Absolutely. Under the hood, this plugin uses `query()`, which returns `total_rows`. If you would like to submit a pull request, I would be happy to accept it. :)

**Comment by chandu0101** [comment]
well i am from scala-js land , If it's a simple change i request you to do it! , if you don't have time please let me know i'll start my experimentation with JS :)

**Comment by nolanlawson** [comment]
Yeah, I'm pretty slammed these days with other projects. :P If you're just getting started, I'd recommend doing it TDD style, because that's what I do for this project:

- check out the code
- read instructions on how to run the tests (basically `npm install && npm test`)
- add a test to `test/test.js`
- add the fix to make it work :)

Since the `query()` response returns `total_rows` already, it should be a piece of cake. E.g. by the time you get to [this line](https://github.com/nolanlawson/pouchdb-quick-search/blob/9f729b35210d6ada3530d45125d2b5f47e9d04ac/index.js#L267), the `res` should already contain the `total_rows`.

**Comment by chandu0101** [comment]
cool , thanks for pointers :)

**Comment by chandu0101** [comment]
done! , please review it :)

**Comment by nolanlawson** [comment]
fixed in d603c7092e866526df8c1a6e668a8b37591f481b
