### ISSUE TITLE
Can I remove the stemmer and keep only the stop word function?

### ISSUE THREAD

**Issue by radisb** [nolanlawson/pouchdb-quick-search#37]
I would like to remove stemming and possibly trimming because I search for non-language words with greek letters in them. Is it possible to do it?

**Comment by nolanlawson** [comment]
Currently this feature is not supported because the point of the whole library is to do natural language processing, which normally involves stemming and trimming.

If you would like to just search for words yourself, I recommend using standard map/reduce and split your text up into whatever "words" you want to index, e.g.:

```js
function (doc) {
  doc.text.toLowerCase().split(' ').forEach(function (word) {
    emit(word);
  });
}
```
