### ISSUE TITLE
Support for partial match for single token query

### ISSUE THREAD

**Issue by aenario** [nolanlawson/pouchdb-quick-search#8]
Full disclosure : I am a total noob when it comes to FTS and have never used lunr before.

From what i understand of the source code, the actual searching of terms from the query is done here : 
https://github.com/nolanlawson/pouchdb-quick-search/blob/master/index.js#L174-L176

Wouldn't it be possible, if queryTerms.length is 1, to do a startKey/endKey search instead ? This way querying for "somethi" would get us docs containg the term "something".

I imagine some adaptions are needed in the rest of the search algorithm. If you think it might work / would merge a PR about this, I will work on it over the week-end.

Thanks

**Comment by danse** [comment]
Do you think that it would be possible to n-gram some fields in order to support partial searches? it would be very valuable. A prefix search is simpler to implement, but it is not as powerful as a partial search on the whole text

**Comment by nolanlawson** [comment]
ngramming is possible, but I haven't implemented it. A pull request would be welcome. :)

**Comment by danse** [comment]
An n-gramming function should be added in the Lunr pipeline, right? I see two problems with this. On one side, it seems that pipeline functions in Lunr can just return a single value, while an n-gramming function would need to yield multiple results. The other problem is that Lunr does not seem to support field specific pipelines. This problem might be mitigated by the interface provided by Lunr and pouchdb-quick-search, which encourages to specify a small number of fields to use for the index

**Comment by nolanlawson** [comment]
Lunr basically takes a sentence as input and outputs an array of tokens:

```js
[lunr, basically, take, sentence, input, output, array, token]
```

So I'm confused now - do you want ngramming between tokens or ngramming within a token?

**Comment by danse** [comment]
I start by saying that i am new to full-text search, so that i don't even fully understand your question. I thought that n-gramming was supposed to go after the tokeniser, and it seemed that Lunr pipeline functions were not suitable for this. Of course a way around could be to use a custom tokeniser, which splits to words parts instead of to words, but this would mix concerns, and make the stemmer and stopword filter useless.

My idea was to add a pipeline function working on tokens, so that:

    'lunr' -> ['l', 'u', 'n', 'r', 'lu', 'un', 'nr', 'lun', 'unr']

**Comment by nolanlawson** [comment]
yeah, that's within-token ngramming. There's also between-token ngrammiing, e.g.

    'teenage mutant ninja turtle' -> ['teenage mutant', 'mutant ninja', 'ninja turtle'], etc.

Everything you mention here is possible, but it's not clear to me whether it should go in Lunr or pouchdb-quick-search. TBH you could probably do what you're describing much easier if you just use [the map/reduce API](http://pouchdb.com/api.html#query_database). :)

**Comment by danse** [comment]
Yep, map/reduce will be, thanks :)

**Comment by rafael-queo** [comment]
Reading all this thread, I didn't understand if it is possible or to search for "flo" in "Desert's flower.jpg". It isn't, right?

**Comment by nolanlawson** [comment]
@rafael-queo: No, it is not.

**Comment by CatchSandeepVaid** [comment]
This is my first post in pouchdb.
@nolanlawson - When you say "one can support prefix search by putting empty documents with IDs equal to whatever you want to do prefix searches on + use allDocs()", does this mean:

1. We need to do this outside this plugin? If yes, this means we cant use prefix search and this plugin together? Is it not possible to add this feature in this plugin only.

2. How should we create these empty docs, using a view (MR) or without MR at the time of saving the original doc to the PouchDB in application's pouch database?

3. How to automatically delete these empty documents automatically when the original documet

**Comment by nolanlawson** [comment]
@CatchSandeepVaid 

What I mean to say is that you can use a separate PouchDB to do the prefix search. That's probably a bit too complicated, though; in this case I would just use map/reduce (see [the map/reduce guide for details](https://pouchdb.com/guides/queries.html)).

Example map function:

```js
function map(doc) {
  doc.words.forEach(function (word) {
    emit(word)
  })
}
```

Then query it using:

```js
db.query('myview/myview', {startkey: 'foo', endkey: 'foo\uffff'}).then(...);
```

^ this will find all documents with any word in the `words` array that starts with the prefix `foo`.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - Thanks for your quick response. This is exactly what i am doing currently. Now do i need to perform tokenizing, stemming and stop-words (may be using lunr) in my view before emitting the word?

Moreover, if i use this approach, i cant use it together with pouchdb-quick-search plugin and wont be able to use this plugin's out of box features like score, highlighting, pagination etc.

Is it possible to add prefix search feature in pouchdb-quick-search plugin itself?

What about partial word search? i.e. if the word is sandeepvaid and if i search for vaid, it should return sandeepvaid. Is there a way to achieve this without using temp views & closure (i.e full database scan on every search)

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - If we want our search to support tokenization, stemming, stop-words, boosting fields, TF-IDF etc. i was thinking if i just use plain lunr in my mobile application (which uses pouchdb as well) as: 

a) For the first time application is started, add all the documents to lunr index.
b) For every change in the document (which should be considered in search), use pouchdb's changes() API to add/update/delete that document to the lunr index. 
NOTE: As my pouchdb is target db for replication, i wont be able to detect between update and add change, so in this case i will first remove document from index and then add the document to index. 

In this way, i can use lunr's index.search() api for searching with all the features that lurn provides. 

I have written basic code for this and it seems working but i am note sure whether this is performant solution or not specially step 1) and are there any issues with this approach?

**Comment by nolanlawson** [comment]
@CatchSandeepVaid Yes, you can use lunr inside of your own map function to accomplish this. I explicitly did not add prefix support in pouchdb-quick-search because I think it's better for people to build their own map functions in that case, since otherwise it could be very confusing to mix stemming with prefix-search. If your app has different needs then I encourage you to write your own map function; it will work exactly the same under the hod as pouchdb-quick-search. :)

**Comment by CatchSandeepVaid** [comment]
@nolanlawson - As discussed, For search to support most of the features, we have 2 approaches. Can you please suggest which approach will be better (or any other approach in your mind).

Approach 1: Use lunr directly on our mobile app i.e Dont use view at all (see my previous comment for more details). but how to achieve auto suggestion with this approach?

Approach 2 : Write our view(MR) and somehow use lunr in it but how? 
   Does lunr provides a API's to do tokenizing, stemming etc which i can call from my view? How can i use lunr scoring etc. features? Moreover, If i do all these in my view, will it become same/similar (reinvent the wheel?) to pouchdb-quick-search?

**Comment by nolanlawson** [comment]
@CatchSandeepVaid There are many ways to do. Lunr does have a private API to just outputs the tokens, which is what I use in this plugin; you can look through the code to find it.

For prefix search, I would just `emit()` all words that you want to be searchable inside of a map function. I would not use Lunr for this. Reason being that when you stem a word with the Porter Stemmer you get rid of a lot of the context (e.g. `politicization` -> `polit`). Hence why I didn't support "autosuggestions" or "prefixes" for pouchdb-quick-search, because I think it's better to just do prefix searching on the raw strings themselves.

**Comment by CatchSandeepVaid** [comment]
@nolanlawson  - We require prefix search, stemming and score features.
Any thoughts on Approach1?   I think its much simpler than approach2, only thing we need to think is when to preserve lunr index (may be before app close/crash if that's possible to detect) and load index (if present) on app start else build index by passing it all docs.

So For approach2, you are saying lunr provides private API for tokenizing, stopwords and stemming. I will check this. What about scoring? Do i have to implement a search method which will use some lunr API which provides score(using TF-IDF?). It seems we have to lot of work in order to implement this.  Moreover will it not become same/similar (reinvent the wheel?) to pouchdb-quick-search with prefix and stemming?

**Comment by nolanlawson** [comment]
@CatchSandeepVaid Not using views is a perfectly valid approach. Not using PouchDB is also a valid approach. Depending on your data size, not having any data on disk (i.e. keeping everything in memory) will be faster.

**Comment by nolanlawson** [comment]
For the Lunr private API, check out [these lines](https://github.com/nolanlawson/pouchdb-quick-search/blob/c6d0cfd5e1b6abbfbcc1fc96a098c70661818b08/lib/index.js#L28-L30). As for TF-IDF, pouchdb-quick-search implements its own version.

**Comment by andresKM** [comment]
@nolanlawson Can I ask about the technics to use in the mobile app?

I`m developing a mobile app on React Native which should include an FTS capabilities on over 10k documents at least.
Can I use Pouch for this? Should I use Pouchy (https://github.com/cdaringe/pouchy)?
If I use Pouchy, that includes Pouch-find, will it be stable and fast, or it`s abandoned?
If I only make server-side PouchDB-server FTS with smth, will It be better? If so, how? What are the steps?

Thanks a lot for your time and passion for the project!

**Comment by nolanlawson** [comment]
pouchdb-quick-search indexing on 10k documents will probably not be very performant in a React Native app. I'd look into raw SQLite and using the built-in FTS4 module instead.

**Comment by aguynamedben** [comment]
Things people here might find valuable for as-you-type search or prefix search:
Overview of trigram/n-gram indexing: https://swtch.com/~rsc/regexp/regexp4.html
FTS5 search indexing in sqlite: https://www.sqlite.org/fts5.html
